---
apiVersion: v1
kind: Pod
metadata:
  name: command-pod
spec:
  containers:
  - name: bb
    image: busybox
    command: ['sh', '-c', 'echo bye']
    #command: ['sh', '-c', 'echo bye && sleep infinity']
  restartPolicy: Never