---
apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod

spec:
  containers:
  - name: redis5
    image: redis:5.0-alpine
  # - name: redis6
  #   image: redis:6.0-alpine
  #   ports:
  #   - containerPort: 6380
  - name: nginx
    image: docker.io/nginx:1.23
    
