---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
  - ReadWriteOnce # volume en lecture/écriture
  resources:
    requests:
      storage: 2Gi # on demande 2 Go d'espace