---
apiVersion: v1
kind: Pod
metadata:
  name: flask-mariadb-pod
spec:
  containers:
  - name: flask-container01
    image: baekdavid/exo3-flask_app:1.0.1
    ports:
    - containerPort: 6379
  # imagePullSecrets:
  # - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: flask
  labels:
    app: flask
spec:
  ports:
    - port: 5000
  selector:
    app: flask
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-pv-claim
  labels:
    app: flask
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  labels:
    app: flask
spec:
  replicas: 8
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - image: baekdavid/exo3-flask_app:1.0.1
        name: flask
        env:
        - name: flask_DB_HOST
          value: flask-mariadb
        - name: flask_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-pass
              key: password
        ports:
        - containerPort: 5000
          name: flask
        volumeMounts:
        - name: flask-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: flask-persistent-storage
        persistentVolumeClaim:
          claimName: flask-pv-claim


---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flask
spec:
  maxReplicas: 8
  minReplicas: 1
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 70
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask
---
apiVersion: v1
kind: Service
metadata:
  name: flask-mariadb
  labels:
    app: flask
spec:
  ports:
    - port: 3306
  selector:
    app: flask
    tier: mariadb
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
  labels:
    app: flask
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-mariadb
  labels:
    app: flask
spec:
  selector:
    matchLabels:
      app: flask
      tier: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flask
        tier: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.0.21
        env:
        - name: mariadb_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-pass
              key: juve
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - name: mariadb-persistent-storage
          mountPath: /var/lib/mariadb
      volumes:
      - name: mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: mariadb-pvc
...